Deposits/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('deposit.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deposit/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('history/', HistoryView.as_view(), name='history'),
    path('map/', MapView.as_view(), name='map'),
    path('area_detail/<int:pk>/', AreaDetailView.as_view(), name='area_detail'),
    path('area_doc/<int:pk>/', GenerateDOCXArea.as_view(), name='area_doc'),
    path('subsoil_users/', SubsoilUsersView.as_view(), name='subsoil_users'),
    path('deposit_balance_chart/', deposit_balance_chart, name='deposit_balance_chart'),
    path('area_balance_chart/', area_balance_chart, name='area_balance_chart'),
    path('subsoil_users_detail/<int:pk>/', SubsoilUserDetailView.as_view(), name='subsoil_user_detail'),
    path('subsoil_users_doc/<int:pk>/', GenerateDOCXSubsoilUser.as_view(), name='subsoil_user_doc'),
    path('localities/', LocalitiesView.as_view(), name='localities'),
    path('locality_detail/<int:pk>/', LocalityDetailView.as_view(), name='locality_detail'),
    path('locality_doc/<int:pk>/', GenerateDOCXLocality.as_view(), name='locality_doc'),
    path('diagram/', DiagramView.as_view(), name='diagram'),
]

deposit/models.py
from django.db import models
from django.urls import reverse


class Area(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True, verbose_name='ID')
    name = models.CharField(db_column='Name', unique=True, max_length=100, verbose_name='Наименование')
    official_portal = models.CharField(db_column='OfficialPortal', max_length=200)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        managed = False
        db_table = 'area'
        verbose_name = 'Район'
        verbose_name_plural = 'Районы'


class Deposit(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True, verbose_name='ID')
    name = models.CharField(db_column='Name', max_length=200, verbose_name='Наименование')
    id_license = models.ForeignKey('License', models.DO_NOTHING, db_column='IDLicense',
                                   verbose_name='Государственный регистрационный номер', related_name='license')
    id_area = models.ForeignKey(Area, models.DO_NOTHING, db_column='IDArea', verbose_name='Район')
    NOT_MASTERED = 'Не освоен'
    POORLY_MASTERED = 'Слабо освоен'
    MASTERED = 'Освоен'
    degree_of_development = [
        (NOT_MASTERED, 'Не освоен'),
        (POORLY_MASTERED, 'Слабо освоен'),
        (MASTERED, 'Освоен')
    ]
    development = models.CharField(db_column='Development', max_length=30, blank=True, null=True,
                                   choices=degree_of_development, default=NOT_MASTERED, verbose_name='Степень освоения')
    a_b_c1 = models.FloatField(db_column='A+B+C1, kg', blank=True, null=True, verbose_name='Запасы (A+B+C1)')
    c2 = models.FloatField(db_column='C2, kg', blank=True, null=True, verbose_name='Запасы (C2)')
    off_balance = models.FloatField(db_column='Off-balance, kg', blank=True, null=True,
                                    verbose_name='Забалансовые запасы')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        managed = False
        db_table = 'deposit'
        verbose_name = 'Месторождение'
        verbose_name_plural = 'Месторождения'


class SubsoilUsers(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True, verbose_name='ID')
    name = models.CharField(db_column='Name', max_length=100, verbose_name='Наименование')
    tin = models.CharField(db_column='TIN', unique=True, max_length=12, verbose_name='ИНН')
    iec = models.CharField(db_column='IEC', max_length=9, blank=True, null=True, verbose_name='КПП')
    psrn_psrnsp = models.CharField(db_column='PSRN/PSRNSP', unique=True, max_length=15, verbose_name='ОГРН')
    date_of_registration = models.DateField(db_column='DateOfRegistration', verbose_name='Дата регистрации')
    director = models.CharField(db_column='Director', max_length=100, verbose_name='Руководитель')

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('subsoil_user_detail', kwargs={'pk': self.id})

    class Meta:
        managed = True
        db_table = 'subsoil_user'
        verbose_name = 'Недропользователь'
        verbose_name_plural = 'Недропользователи'


class License(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True, verbose_name='ID')
    name = models.CharField(db_column='Name', max_length=15, verbose_name='Наименование')
    id_subsoil_users = models.ForeignKey(SubsoilUsers, models.DO_NOTHING, db_column='IDSubsoilUsers',
                                         verbose_name='Недропользователь')
    start_date = models.DateField(db_column='StartDate', verbose_name='Дата начала срока действия лицензии')
    end_date = models.DateField(db_column='EndDate', verbose_name='Дата окончания срока действия лицензии')
    cancelled = models.BooleanField(db_column='Cancelled', verbose_name='Действие лицензии прекращено')
    destination = models.CharField(db_column='Destination', max_length=255, verbose_name='Целевое назначение лицензии')
    diversion = models.CharField(db_column='Diversion', max_length=30, verbose_name='Статус отвода')

    def __str__(self):
        return f'{self.name}'

    def get_deposit(self):
        deposit = self.license.first()
        return deposit.name if deposit else '-'

    get_deposit.short_description = 'Месторождение'

    class Meta:
        managed = False
        db_table = 'license'
        verbose_name = 'Лицензия'
        verbose_name_plural = 'Лицензии'


class Localities(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True, verbose_name='ID')
    name = models.CharField(db_column='Name', max_length=100, verbose_name='Наименование')
    id_area = models.ForeignKey(Area, models.DO_NOTHING, db_column='IDArea', verbose_name='Район',
                                related_name='localities')
    id_locality_type = models.ForeignKey('LocalitiesType', models.DO_NOTHING, db_column='IDLocalityType',
                                         verbose_name='Тип')

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('locality_detail', kwargs={'pk': self.id})

    class Meta:
        managed = False
        db_table = 'locality'
        verbose_name = 'Населенный пункт'
        verbose_name_plural = 'Населенные пункты'


class LocalitiesType(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True, verbose_name='ID')
    name = models.CharField(db_column='Name', unique=True, max_length=100, verbose_name='Наименование')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        managed = False
        db_table = 'locality_type'
        verbose_name = 'Тип населенных пунктов'
        verbose_name_plural = 'Типы населенных пунктов'


class LocalitiesDeposit(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True, verbose_name='ID')
    id_locality = models.ForeignKey(Localities, models.DO_NOTHING,
                                    db_column='IDLocality', verbose_name='Населенный пункт')
    id_deposit = models.ForeignKey(Deposit, models.DO_NOTHING, db_column='IDDeposit', verbose_name='Месторождение')
    direction = models.CharField(db_column='Direction', max_length=20, verbose_name='Направление')
    distance = models.FloatField(db_column='Distance', verbose_name='Расстояние')

    def __str__(self):
        return f'{self.id_locality} - {self.id_deposit}'

    class Meta:
        managed = False
        db_table = 'locality_deposit'
        verbose_name = 'Связь месторождений с населенными пунктами'
        verbose_name_plural = 'Связи месторождений с населенными пунктами'

deposit/templates/area_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Информация о районе {{ area.name }}{% endblock title %}
{% block content %}
    <section class="municipality_detail-section">
        <div class="container">
            <h1 class="heading">Информация о районе {{ area.name }}</h1>
            <div class="row" style="margin-top: 50px; justify-content: center">
                <div class="col-md-8">
                    {% if area.official_portal != '' %}
                        <a target="_blank" href="{{ area.official_portal }}"><p>
                            Официальный портал Забайкальского края. {{ area.name }} район <span
                                class="a_official_portal">{{ area.official_portal }}</span></p></a>
                    {% else %}
                        <p>В настоящий момент у данного района не официального портала.</p>
                    {% endif %}
                    {% if area.deposit_set.count == 0 %}
                        <p>В данном районе нет разрабатывающихся месторождений.</p>
                    {% else %}
                        <p>В данной таблице представлена информация о месторождениях, которые
                            разрабатываются в районе</p>
                        <div class="table-responsive">
                            <table class="table table-bordered caption-top">
                                <caption>Информация о месторождения</caption>
                                <thead>
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Месторождение</th>
                                    <th scope="col">Недропользователь</th>
                                    <th scope="col">Лицензия</th>
                                    <th scope="col">Действие лицензии прекращено</th>
                                    <th scope="col">Целевое назначение лицензии</th>
                                    <th scope="col">Запасы месторождения (A+B+C1), кг</th>
                                    <th scope="col">Запасы месторождения (C2), кг</th>
                                    <th scope="col">Забалансовые запасы месторождения, кг</th>
                                    <th scope="col">Суммарные запасы месторождения, кг</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for d in deposit %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>{{ d.name }}</td>
                                        <td>
                                            <a href="{% url 'subsoil_user_detail' d.id_license.id_subsoil_users.pk %}">
                                                {{ d.id_license.id_subsoil_users.name }}</a>
                                        </td>
                                        <td>{{ d.id_license.name }}</td>
                                        <td>{{ d.id_license.cancelled|yesno:"Да, Нет" }}</td>
                                        <td>{{ d.id_license.destination }}</td>
                                        <td>{{ d.a_b_c1|default_if_none:"Отсутствуют" }}</td>
                                        <td>{{ d.c2|default_if_none:"Отсутствуют" }}</td>
                                        <td>{{ d.off_balance|default_if_none:"Отсутствуют" }}</td>
                                        {% if d.a_b_c1 == None and d.c2 == None and d.off_balance == None %}
                                            <td>Отсутствуют</td>
                                        {% elif d.a_b_c1 == None and d.c2 == None %}
                                            <td>{{ d.off_balance }}</td>
                                        {% elif d.a_b_c1 == None and d.off_balance == None %}
                                            <td>{{ d.c2 }}</td>
                                        {% elif d.c2 == None and d.off_balance == None %}
                                            <td>{{ d.a_b_c1 }}</td>
                                        {% elif d.a_b_c1 == None %}
                                            <td>{{ d.c2|add:d.off_balance }}</td>
                                        {% elif d.c2 == None %}
                                            <td>{{ d.a_b_c1|add:d.off_balance }}</td>
                                        {% elif d.off_balance == None %}
                                            <td>{{ d.a_b_c1|add:d.c2 }}</td>
                                        {% else %}
                                            <td>{{ d.a_b_c1|add:d.c2|add:d.off_balance }}</td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                <tr>
                                    <th scope="row">Итого</th>
                                    <td colspan="5"></td>
                                    <td>{{ a_b_c1.abc1|default_if_none:"Отсутствуют" }}</td>
                                    <td>{{ c2.c2|default_if_none:"Отсутствуют" }}</td>
                                    <td>{{ off_balance.off_balance|default_if_none:"Отсутствуют" }}</td>
                                    {% if a_b_c1.abc1 == None and c2.c2 == None and off_balance.off_balance == None %}
                                        <td>Отсутствуют</td>
                                    {% elif a_b_c1.abc1 == None and c2.c2 == None %}
                                        <td>{{ off_balance.off_balance }}</td>
                                    {% elif a_b_c1.abc1 == None and off_balance.off_balance == None %}
                                        <td>{{ c2.c2 }}</td>
                                    {% elif c2.c2 == None and off_balance.off_balance == None %}
                                        <td>{{ a_b_c1.abc1 }}</td>
                                    {% elif a_b_c1.abc1 == None %}
                                        <td>{{ c2.c2|add:off_balance.off_balance }}</td>
                                    {% elif c2.c2 == None %}
                                        <td>{{ a_b_c1.abc1|add:off_balance.off_balance }}</td>
                                    {% elif off_balance.off_balance == None %}
                                        <td>{{ a_b_c1.abc1|add:c2.c2 }}</td>
                                    {% else %}
                                        <td>{{ a_b_c1.abc1|add:c2.c2|add:off_balance.off_balance }}</td>
                                    {% endif %}
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <p></p>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <button type="button" class="btn btn-primary print">Отчет PDF</button>
                            <a href="{% url 'area_doc' area.pk %}" class="a_doc">
                                <button type="button" class="btn btn-primary print button_doc">Отчет DOCX</button>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block js %}
    <script src="{% static 'js/print_pdf.js' %}"></script>
{% endblock js %}

deposit/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Кодировка веб-страницы -->
    <meta charset="utf-8">
    <!-- Настройка viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Золото Забайкалья{% endblock title %}</title>
    <!-- CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    {% block css %}
    {% endblock css %}
</head>
<body>
<!--Navigation-->
<div class="main">
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'base' %}">Золото Забайкалья</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'map' %}">Карта Забайкальского края</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'subsoil_users' %}">Недропользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'localities' %}">Населенные пункты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'diagram' %}">Диаграммы</a>
                    </li>
                    {#                    <li class="nav-item">#}
                    {#                        <a class="nav-link" href="{% url 'test' %}">Тестовый</a>#}
                    {#                    </li>#}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
        <div class="container-fluid main">
        <div id="myCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel"
             data-bs-interval="3000">
            <div class="carousel-inner">
                <div class="carousel-inner">
                    <div class="carousel-item active background a">
                        <div class="carousel-caption">
                            <h5 class="title">Золото Забайкалья</h5>
                            <p class="subtitle">История развития добычи золота в Забайкальском крае</p>
                            <div class="col-xs-12 explore">
                                <a href="{% url 'history' %}">
                                    <button type="button" class="btn btn-lg explorebtn">ЧИТАТЬ</button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item background b">
                        <div class="carousel-caption">
                            <h5 class="title">Золото Забайкалья</h5>
                            <p class="subtitle">История развития добычи золота в Забайкальском крае</p>
                            <div class="col-xs-12 explore">
                                <a href="{% url 'history' %}">
                                    <button type="button" class="btn btn-lg explorebtn">ЧИТАТЬ</button>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item background c">
                        <div class="carousel-caption">
                            <h5 class="title">Золото Забайкалья</h5>
                            <p class="subtitle">История развития добычи золота в Забайкальском крае</p>
                            <div class="col-xs-12 explore">
                                <a href="{% url 'history' %}">
                                    <button type="button" class="btn btn-lg explorebtn">ЧИТАТЬ</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
    </div>
    <!--Footer-->
    {% block footer %}
        <footer class="bg-dark fixed-bottom" style="  flex-shrink: 0;">
            <div class="container"><p class="m-0 text-center text-white">&copy;Забайкальский государственный университет
                2022</p></div>
        </footer>
    {% endblock footer %}
    {% block scroll %}
        <img src="{% static 'img/up.webp' %}" alt="Наверх" title="Наверх" class="GoTop">
        <img src="{% static 'img/down.webp' %}" alt="Вниз" title="Вниз" class="GoBottom">
    {% endblock scroll %}
    <!--JS-->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scroll.js' %}"></script>
    {% block js %}
    {% endblock js %}
</body>
</html>

deposit/templates/diagram.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Диаграммы по запасам месторождений{% endblock title %}
{% block content %}
    <section class="subsoil_users-section">
        <div class="container">
            <h1 class="heading">Диаграммы по запасам месторождений</h1>
            <div class="row" style="margin-top: 50px; justify-content: center">
                <div class="col-md-8">
                    <p>На данной странице представлены диаграммы по запасам месторождений. Для того чтобы посмотреть
                        диаграмму, нажмите на ее название.</p>
                    <hr>
                    <div class="details">
                        <details>
                            <summary>Диаграмма распределения запасов месторождений между недропользователями</summary>
                            <p class="mt-4 mb-4" style="font-size: 16px">Для получения информации о запасах наведите на
                                сектор диаграммы</p>
                            <h5 class="mt-4 mb-4" style="text-align: center">Распределение запасов месторождений между
                                недропользователями</h5>
                            <div id="container_diagram" style="padding-bottom: 20px">
                                <canvas id="deposit_balance_chart"
                                        data-url="{% url 'deposit_balance_chart' %}"></canvas>
                            </div>
                        </details>
                        <hr>
                        <details>
                            <summary>Диаграмма распределения запасов месторождений по районам</summary>
                            <p class="mt-4 mb-4" style="font-size: 16px">Для получения информации о запасах наведите на
                                сектор диаграммы</p>
                            <h5 class="mt-4 mb-5" style="text-align: center">Распределение запасов месторождений по
                                районам</h5>
                            <div id="container_diagram">
                                <canvas id="area_balance_chart" data-url="{% url 'area_balance_chart' %}"></canvas>
                            </div>
                        </details>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block js %}
    <script src="{% static 'js/chart.min.js' %}"></script>
    <script src="{% static 'js/deposit_balance_chart.js' %}"></script>
    <script src="{% static 'js/area_balance_chart.js' %}"></script>
{% endblock js %}

deposit/templates/history.html
{% extends 'base.html' %}
{% load static %}
{% block title %}История развития золотодобычи в Забайкальском крае{% endblock title %}
{% block content %}
    <section class="history-section">
        <div class="container">
            <h1 class="heading">История развития золотодобычи в Забайкальском крае</h1>
            <div class="row" style="margin-top: 50px; justify-content: center">
                <div class="col-md-8">
                    <div class="toc-container">
                        <p class="toc-title">Оглавление</p>
                        <ul class="toc-list">
                            <li><a href="#i-1">С чего началась добыча на Забайкалье</a></li>
                            <li><a href="#i-2">Как разрабатывают современные россыпи Забайкалья</a></li>
                            <li><a href="#i-3">Перспективы новых месторождений</a></li>
                            <li><a href="#i-4">Кем и как добываются</a></li>
                            <li><a href="#i-5">Методы добычи</a></li>
                            <li><a href="#i-6">Объемы добычи</a></li>
                            <li><a href="#i-7">Использованные источники</a></li>
                        </ul>
                    </div>
                    <h2><span id="i-1">С чего началась добыча на Забайкалье</span></h2>
                    <p>Первое золото Забайкальского края было добыто попутно в 1702 г., когда разведали Нерчинское
                        месторождение серебряной руды. Спустя два года (1704 г.) было завершено строительство
                        Нерчинского плавильного завода. Из трёх тонн переплавляемой руды, содержащей серебро,
                        удавалось извлечь примерно 16 кг золота.</p>
                    <p>Карийская россыпь, открытая в 1838 г., положила начало «золотой лихорадке» Забайкалья. С этого
                        момента месторождения россыпного и коренного золота начали находить по всему региону.
                        В историю же вошла дата 31 мая 1843 г. В этот день было разрешено работать на приисках
                        частным лицам западной части Забайкалья. В Восточном Забайкалье это стало возможно лишь
                        спустя 20 лет.</p>
                    <h2><span id="i-2">Как разрабатывают современные россыпи Забайкалья</span></h2>
                    <p>Такие участки чаще всего отрабатывают небольшие артели старателей, а не золотодобывающие гиганты.
                        Работы ведутся промывочным способом. До начала сезона ведётся масштабная подготовка:
                        вырубка леса, расчистка дорог, прокладывание канала для отвода русла реки. С наступлением
                        оттепели делается вскрыша, т.е. с помощью экскаваторов и бульдозеров убирается несколько метров
                        горной породы, скрывающей золотоносные пески.</p>
                    <p>Если порода не пригодна для использования в строительной промышленности, она отвозится в отвалы.
                        Слой с полезными ископаемыми (там может быть и свинец, и серебро) подвергается промывке.
                        Для этого используется вода с отведённого русла и специальное оборудование. В бункер
                        промприбора загружается обрабатываемая порода, и под воздействием напора воды на трафарете
                        остаётся металл. Далее он отправляется на аффинажную фабрику, где очищается из примесей и
                        превращается в чистое золото.</p>
                    <h2><span id="i-3">Перспективы новых месторождений</span></h2>
                    <p>Согласно геологическим данным, в регионе имеется свыше 1000 проявлений драгоценного металла. В
                        эту цифру входят и золоторудные участки, и золотоносные пески. Также возможны месторождения на
                        дне Байкала. Но для точного подсчёта и утверждения запасов требуются дополнительные
                        геологоразведочные работы и значительные финансовые ресурсы.</p>
                    <p class="history-img"><img src="{% static 'img/history1.jpg' %}"></p>
                    <h2><span id="i-4">Кем и как добываются</span></h2>
                    <p>На сегодняшний день золотоносные месторождения разрабатывает около 50 предприятий. С учётом
                        потенциала региона их могло бы быть больше. Но нестабильная экономическая ситуация в стране
                        тормозит развитие добычной отрасли. К заброшенным и труднодоступным месторождениям проявляется
                        большой интерес со стороны Китая, готового инвестировать в добычу.</p>
                    <p>За 2020 год больше всего золота добыли следующие предприятия:</p>
                    <ul>
                        <li>Быстринский ГОК - 7,5 тонны</li>
                        <li>ГК «Мангазея-Майнинг» - 1,6 тонны</li>
                        <li>ПАО " Ксеньевский прииск" - 1,08 тонны</li>
                        <li>ОАО Прииск "Усть-Кара" - 1,08 тонны</li>
                        <li>ОАО "Прииск "Соловьевский" - 0,319 тонны</li>
                    </ul>
                    <p class="history-img"><img src="{% static 'img/history2.jpg' %}"></p>
                    <h2><span id="i-5">Методы добычи</span></h2>
                    <p>Россыпи Забайкалья обрабатываются промывочным способом, описанным выше. Золоторудные
                        месторождения осваиваются с помощью кучного выщелачивания. Его суть заключается в следующем.
                        Руда укладывается слоями на специальные поддоны. Под воздействием цианистого раствора
                        происходит химическая реакция, в результате которой выщелачивается золото и серебро.</p>
                    <h2><span id="i-6">Объемы добычи</span></h2>
                    <p>Объёмы добычи драгоценных металлов в регионе — стабильно высокие и имеют тенденцию к увеличению.
                        Общий объём добытого в Забайкалье ценного ресурса в 2020 году составил 11 тонн.</p>
                    <p>Сегодня Забайкальский край считается одним из самых богатых на полезные ископаемые регионов
                        России. К сожалению, из-за отсутствия инвестирования в нужном объёме, его потенциал не
                        развивается должным образом.</p>
                    <h2><span id="i-7">Использованные источники</span></h2>
                    <ol>
                        <li><a href="https://zhazhdazolota.ru/dobycha/v-zabajkalskom-krae">Добыча золота в Забайкальском
                            крае: список месторождений и золотодобывающих компаний, история, технологии и
                            перспективы</a>
                        </li>
                        <li><a href="https://cherish-centr.ru/o-zolote/zolotodobycha-zabajkalskij-kraj.html">Добыча
                            золота в Забайкальском крае: список месторождений и рудников, добывающие компании</a>
                        </li>
                        <li><a href="http://www.eruda.ru/gdp/zabaykalsky_kray.htm">Забайкальский край новости
                            золотодобывающих, угледобывающих, горнодобывающих компании 2022 г.</a>
                        </li>
                        <li><a href="http://www.eruda.ru/news_1/1108_rossii_dobyli_340_t_zolota_v_2020_godu.htm">Итоги
                            золотодобычи в РФ в 2020 году/данные минфина /новости горнодобывающих, угледобывающих,
                            нефтегазодобывающих компаний/работа вакансии</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

deposit/templates/map.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Карта Забайкальского края{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/leaflet.css'%}"/>
{% endblock css %}
{% block content %}
    <div id="mapid"></div>
{% endblock content %}
{% block footer %}
{% endblock footer %}
{% block scroll %}
{% endblock scroll %}
{% block js %}
    <script src="{% static 'js/leaflet.js'%}"></script>
    <script src="{% static 'js/zk_districts.js' %}"></script>
    <script src="{% static 'js/map.js' %}"></script>
{% endblock js %}